### ISSUE TITLE
Build error under 4.04.1+32bit

### ISSUE THREAD

**Issue by kettlebell** [janestreet/async_js#1]
Using Janestreet opam-repository, the build fails (tested under Ubuntu 16.04 and MacOS 10.12) with the following error:

```
File "ppx/ppx_js_driver.ml", line 2, characters 18-34:
Error: Unbound value Ppx_js.js_mapper
Hint: Did you mean mapper?
```

**Comment by imeckler** [comment]
This also happens on  4.04.1 (not 32 bit) for me.

**Comment by hhugo** [comment]
similar to https://github.com/janestreet/opam-repository/issues/7

**Comment by hhugo** [comment]
I believe this is fixed. closing.
